# ZeroWall - Runtime Sysctl Tunables
# Applied via sysctl -f /etc/sysctl.conf

# Security Hardening
net.inet.ip.redirect=0
net.inet.ip.sourceroute=0
net.inet.ip.accept_sourceroute=0
net.inet.icmp.log_redirect=0
net.inet.icmp.drop_redirect=1
net.inet.ip.stealth=1
net.inet.tcp.path_mtu_discovery=1
net.inet.tcp.drop_synfin=1

# IP Forwarding
net.inet.ip.forwarding=1
net.inet.ipv6.forwarding=1

# Fast Forwarding (Try to bypass full stack packet processing)
net.inet.ip.fastforwarding=1

# TCP Performance
net.inet.tcp.sackedelay=0
net.inet.tcp.recvbuf_auto=1
net.inet.tcp.sendbuf_auto=1
net.inet.tcp.recvbuf_inc=16384
net.inet.tcp.sendbuf_inc=16384
net.inet.tcp.recvspace=65536
net.inet.tcp.sendspace=65536

# UNIX Domain Socket Performance (for zwapi <-> zwconfigd)
net.local.stream.recvspace=65536
net.local.stream.sendspace=65536

# pf Monitoring
net.pf.filter_local=1
